FROM mcr.microsoft.com/devcontainers/javascript-node:22

# Install additional packages if needed
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends git
